recursive: true
all: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
dir: "skiff/mocks/{{ base .SrcPackageName }}mocks"
pkgname: "{{ base .SrcPackageName }}mocks"
structname: "{{.InterfaceName}}"
template: testify
packages:
  github.com/skiff-sh/sdk-go/skiff: { }
