// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package skiffmocks

import (
	"github.com/skiff-sh/api/go/skiff/plugin/v1alpha1"
	"github.com/skiff-sh/sdk-go/skiff"
	mock "github.com/stretchr/testify/mock"
)

// NewPlugin creates a new instance of Plugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *Plugin {
	mock := &Plugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Plugin is an autogenerated mock type for the Plugin type
type Plugin struct {
	mock.Mock
}

type Plugin_Expecter struct {
	mock *mock.Mock
}

func (_m *Plugin) EXPECT() *Plugin_Expecter {
	return &Plugin_Expecter{mock: &_m.Mock}
}

// WriteFile provides a mock function for the type Plugin
func (_mock *Plugin) WriteFile(ctx *skiff.Context, req *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 *v1alpha1.WriteFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*skiff.Context, *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(*skiff.Context, *v1alpha1.WriteFileRequest) *v1alpha1.WriteFileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.WriteFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*skiff.Context, *v1alpha1.WriteFileRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Plugin_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type Plugin_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx *skiff.Context
//   - req *v1alpha1.WriteFileRequest
func (_e *Plugin_Expecter) WriteFile(ctx interface{}, req interface{}) *Plugin_WriteFile_Call {
	return &Plugin_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, req)}
}

func (_c *Plugin_WriteFile_Call) Run(run func(ctx *skiff.Context, req *v1alpha1.WriteFileRequest)) *Plugin_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *skiff.Context
		if args[0] != nil {
			arg0 = args[0].(*skiff.Context)
		}
		var arg1 *v1alpha1.WriteFileRequest
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.WriteFileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Plugin_WriteFile_Call) Return(writeFileResponse *v1alpha1.WriteFileResponse, err error) *Plugin_WriteFile_Call {
	_c.Call.Return(writeFileResponse, err)
	return _c
}

func (_c *Plugin_WriteFile_Call) RunAndReturn(run func(ctx *skiff.Context, req *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error)) *Plugin_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
