// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package issuemocks

import (
	"github.com/skiff-sh/api/go/skiff/plugin/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// NewPluginIssue creates a new instance of PluginIssue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPluginIssue(t interface {
	mock.TestingT
	Cleanup(func())
}) *PluginIssue {
	mock := &PluginIssue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PluginIssue is an autogenerated mock type for the PluginIssue type
type PluginIssue struct {
	mock.Mock
}

type PluginIssue_Expecter struct {
	mock *mock.Mock
}

func (_m *PluginIssue) EXPECT() *PluginIssue_Expecter {
	return &PluginIssue_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type PluginIssue
func (_mock *PluginIssue) Issue() *v1alpha1.Issue {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *v1alpha1.Issue
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.Issue); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Issue)
		}
	}
	return r0
}

// PluginIssue_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type PluginIssue_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
func (_e *PluginIssue_Expecter) Issue() *PluginIssue_Issue_Call {
	return &PluginIssue_Issue_Call{Call: _e.mock.On("Issue")}
}

func (_c *PluginIssue_Issue_Call) Run(run func()) *PluginIssue_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PluginIssue_Issue_Call) Return(issue *v1alpha1.Issue) *PluginIssue_Issue_Call {
	_c.Call.Return(issue)
	return _c
}

func (_c *PluginIssue_Issue_Call) RunAndReturn(run func() *v1alpha1.Issue) *PluginIssue_Issue_Call {
	_c.Call.Return(run)
	return _c
}
