// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package issue

import (
	"github.com/skiff-sh/api/go/skiff/plugin/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// newMockPluginIssue creates a new instance of mockPluginIssue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPluginIssue(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPluginIssue {
	mock := &mockPluginIssue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPluginIssue is an autogenerated mock type for the PluginIssue type
type mockPluginIssue struct {
	mock.Mock
}

type mockPluginIssue_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPluginIssue) EXPECT() *mockPluginIssue_Expecter {
	return &mockPluginIssue_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type mockPluginIssue
func (_mock *mockPluginIssue) Issue() *v1alpha1.Issue {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 *v1alpha1.Issue
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.Issue); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Issue)
		}
	}
	return r0
}

// mockPluginIssue_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type mockPluginIssue_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
func (_e *mockPluginIssue_Expecter) Issue() *mockPluginIssue_Issue_Call {
	return &mockPluginIssue_Issue_Call{Call: _e.mock.On("Issue")}
}

func (_c *mockPluginIssue_Issue_Call) Run(run func()) *mockPluginIssue_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockPluginIssue_Issue_Call) Return(issue *v1alpha1.Issue) *mockPluginIssue_Issue_Call {
	_c.Call.Return(issue)
	return _c
}

func (_c *mockPluginIssue_Issue_Call) RunAndReturn(run func() *v1alpha1.Issue) *mockPluginIssue_Issue_Call {
	_c.Call.Return(run)
	return _c
}
