// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package skiff

import (
	"github.com/skiff-sh/api/go/skiff/plugin/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// newMockPlugin creates a new instance of mockPlugin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockPlugin(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockPlugin {
	mock := &mockPlugin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockPlugin is an autogenerated mock type for the Plugin type
type mockPlugin struct {
	mock.Mock
}

type mockPlugin_Expecter struct {
	mock *mock.Mock
}

func (_m *mockPlugin) EXPECT() *mockPlugin_Expecter {
	return &mockPlugin_Expecter{mock: &_m.Mock}
}

// WriteFile provides a mock function for the type mockPlugin
func (_mock *mockPlugin) WriteFile(ctx *Context, req *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 *v1alpha1.WriteFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*Context, *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(*Context, *v1alpha1.WriteFileRequest) *v1alpha1.WriteFileResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.WriteFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*Context, *v1alpha1.WriteFileRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockPlugin_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type mockPlugin_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - ctx *Context
//   - req *v1alpha1.WriteFileRequest
func (_e *mockPlugin_Expecter) WriteFile(ctx interface{}, req interface{}) *mockPlugin_WriteFile_Call {
	return &mockPlugin_WriteFile_Call{Call: _e.mock.On("WriteFile", ctx, req)}
}

func (_c *mockPlugin_WriteFile_Call) Run(run func(ctx *Context, req *v1alpha1.WriteFileRequest)) *mockPlugin_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *Context
		if args[0] != nil {
			arg0 = args[0].(*Context)
		}
		var arg1 *v1alpha1.WriteFileRequest
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.WriteFileRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockPlugin_WriteFile_Call) Return(writeFileResponse *v1alpha1.WriteFileResponse, err error) *mockPlugin_WriteFile_Call {
	_c.Call.Return(writeFileResponse, err)
	return _c
}

func (_c *mockPlugin_WriteFile_Call) RunAndReturn(run func(ctx *Context, req *v1alpha1.WriteFileRequest) (*v1alpha1.WriteFileResponse, error)) *mockPlugin_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
